### ISSUE TITLE
PR in Jenkins Repo

### ISSUE THREAD

**Issue by chelnak** [agovindaraju/vmware-vrealize-orchestrator#3]
Hi I made a PR back in Feb on the Jenkins repo for this plugin..

https://github.com/jenkinsci/vmware-vrealize-orchestrator-plugin/pull/1

Is that the correct place or should it be here?

**Comment by chelnak** [comment]
Thanks for merging. It will be good to see the changes in a future release!  :-)

**Comment by agovindaraju** [comment]
I am having issues with my account for releasing. It keeps showing unauthorized. Please feel free to make a new release.  I have added you as admin.
